package main

import (
	"github.com/ekastn/hms-api/internal/app"

	_ "github.com/ekastn/hms-api/docs" // docs is generated by Swag CLI, you have to import it.
)

//	@title			HMS API Documentation
//	@version		1.0
//	@description	This is the API documentation for the Hospital Management System.
//	@termsOfService	http://swagger.io/terms/

//	@contact.name	API Support
//	@contact.url	https://github.com/ekastn
//	@contact.email	eka@voixes.studio

//	@license.name	Apache 2.0
//	@license.url	http://www.apache.org/licenses/LICENSE-2.0.html

//	@host		localhost:5021
//	@BasePath	/api

// @securityDefinitions.apikey	ApiKeyAuth
// @in							header
// @name						Authorization
func main() {
	app := app.App{}
	app.Run()
}
